### ISSUE TITLE
Deployment failure to he RSConnect server

### ISSUE THREAD

**Issue by EBukin** [EBukin/devPTIpack#27]
Dear @takaakimasaki  and @ifeanyi588 ,

I finally got to the roots of the app's deployment problem. It is in the fact that our app's have file `metadata.rmd` in the `app-data` folder. Basically, when the deployment manifest is generated, `rsconnect` package adds to the manifest any library that is present in the `metadata.rmd` (or any .R/.Rmd file in the app root) and it makes our app too large to deploy. See also #26 .

- [ ] Please take one of the existing apps and clean it folder keeping in only  `app.R` and any other non-R file.
- [ ] Redeploy this app to the WB RSConnect server. 
- [ ] Report below if deployment worker.

Hope this will resolve the deployment problem.

**Comment by takaakimasaki** [comment]
@EBukin This is amazing! I now was able to deploy the app to the Bank server! Thanks for looking into this.
